export const items = [
  {
    itemId: 0,
    name: 'Item 1',
    price: 200,
    image: 'assets/FoodItems/item1.jpeg',
    quantity: 1,
    instructions: 'NA',
    addOn: [],
  },
  {
    itemId: 1,
    name: 'Item 2',
    price: 700,
    image: 'assets/FoodItems/item2.jpg',
    quantity: 1,
    instructions: 'NA',
    addOn: [],
  },
  {
    itemId: 2,
    name: 'Item 3',
    price: 450,
    image : 'assets/FoodItems/item3.jpg',
    quantity: 1,
    instructions: 'NA',
    addOn: [],
  },
  {
    itemId: 3,
    name: ' Item 4',
    price: 280,
    image : 'assets/FoodItems/item4.jpg',
    quantity: 1,
    instructions: 'NA',
    addOn: [],
  },
  {
    itemId: 4,
    name: 'Item 5',
    price: 120,
    image : 'assets/FoodItems/item5.jpg',
    quantity: 1,
    instructions: 'NA',
    addOn: [],
  },
  {
    itemId: 5,
    name: ' Item 6',
    price: 340,
    image : 'assets/FoodItems/item6.jpg',
    quantity: 1,
    instructions: 'NA',
    addOn: [],
  },
];
